ADF-23 | Developer console update, env and help commands
TinyTakinTeller/GodotProjectZero pull request #16
Opened 2024-07-11 11:40 UTC by alexmunoz502

![image](https://github.com/TinyTakinTeller/GodotProjectZero/assets/41115154/b7d4ebb3-3c36-4150-944b-ea5448567af2)

2024-07-11 11:41 UTC, alexmunoz502 commented on global/autoload/audio/audio.gd
> +	# if tab_data.id == DarknessScreen.TAB_DATA_ID:
this isn't part of this PR, but a work around for an unrelated issue

2024-07-11 11:42 UTC, alexmunoz502 commented
decided to change 'gamemode' to 'env' from the ticket in trello. LMK if you prefer gamemode instead

2024-07-11 20:24 UTC, TinyTakinTeller requested changes
Env makes sense for OS command.

For gamemode I imagined a different command - being able to change the params in console (“global/const/game.gd”) 👀 i.e. refactor that const node to a global node and allow to switch between the two dictionaries - what do you think about this idea?

2024-07-12 00:23 UTC, alexmunoz502 commented
> Env makes sense for OS command.
> 
> For gamemode I imagined a different command - being able to change the params in console (“global/const/game.gd”) 👀 i.e. refactor that const node to a global node and allow to switch between the two dictionaries - what do you think about this idea?
> 
> (If you think it is better to leave those as const i.e. only allow manual change in code before game startup, I'm also fine with that and will approve merge.)

Yeah, I think that it should just be set before running. We could have different environment presets that can be selected between on startup. Is there a use case where you think it might be necessary to edit constants?

2024-07-12 23:34 UTC, TinyTakinTeller approved these changes

2024-07-13 14:20 UTC, merged